### ISSUE TITLE
No output when training on CXP

### ISSUE THREAD

**Issue by XuZikang** [LalehSeyyed/CheXclusion#4]
Hi,

I cloned your code and run /CXP/main.py directly with my server (after installed f1.yml). However, the only output is 

```shell
(f1)  ~/Documents/phd_code/CheXclusion/CXP/ [main*] python main.py
Validation_df size: 44683
Train_df size 178731
Test_df size 234
Train Mode
Validation_df path 44683
Train_df path 178731
Using 4 GPUs
  0%|                                                                                               | 0/65 [00:00<?, ?it/s]
Epoch 0/64
```

And after this, I waited about 10 hours but there is no output, while when I open "nvidia-smi", the program is still occupying my GPUs.

Could you help me to solve this issue? Thank you very much!

**Comment by XuZikang** [comment]
I annotated the line in train.py, and it now works.

```python
# os.environ['CUDA_LAUNCH_BLOCKING'] = "1"
```

**Comment by LalehSeyyed** [comment]
The was not set up for multiple GPU. I am happy you figured it out.
