### ISSUE TITLE
mimic image level labels?

### ISSUE THREAD

**Issue by Aliktk** [LalehSeyyed/CheXclusion#6]
Thank you for this interesting repo.
I am trying to explore the MIMIC dataset where I get the dataset but I can't find any labels in CSV format. 
If ground truth image-level labels are there please share them. 
Thank you

**Comment by LalehSeyyed** [comment]
Hi

You need to contact physionet, mimic team to get labels. We are not allowed
to share labels due to data sharing agreement.

Best
Laleh

**Comment by Aliktk** [comment]
thankyou @LalehSeyyed  for the quick response. I have both versions of data and labels for a specific folder, not for the image name. you can check out here:
[mimic-cxr-2.0.0-chexpert.csv](https://github.com/LalehSeyyed/CheXclusion/files/8685081/mimic-cxr-2.0.0-chexpert.csv)

**Comment by LalehSeyyed** [comment]
*The file that you are using is correct. The labels are for a particular
folder, as all images from a particular study have the same labels. It is
not possible to differentiate between which image from a study was used for
which diagnosis.*

**Comment by Aliktk** [comment]
@LalehSeyyed  Thank you I sort it out.
